import yaml
from json import loads
from unittest import TestCase

from tests.utils import fixture
from renderers.swagger import SwaggerRenderer
from parser import HttpRequest


class TestSwaggerRender(TestCase):

    def test_render(self):
        requests = HttpRequest.parse_file(fixture("file_one.http"))

        swagger_json = SwaggerRenderer.json(requests)
        swagger = loads(swagger_json)

        self.assertEqual(swagger['info']['title'], "Generated by Strut")
        self.assertEqual(len(swagger['paths']), 1)

    def test_render_three(self):
        requests = HttpRequest.parse_file(fixture("file_three.http"))

        swagger_json = SwaggerRenderer.json(requests)
        swagger = loads(swagger_json)

        self.assertEqual(swagger['info']['title'], "Generated by Strut")
        self.assertEqual(len(swagger['paths']), 1) # BUG shouldn't this be 2?
        self.assertTrue('responses' in swagger['paths']["/kittens"]["get"])


    def test_render_yaml(self):
        requests = HttpRequest.parse_file(fixture("file_one.http"))

        swagger = yaml.load(SwaggerRenderer.yaml(requests))

        self.assertEqual(swagger['info']['title'], "Generated by Strut")
        self.assertEqual(len(swagger['paths']), 1)
