import yaml
from json import loads
from unittest import TestCase

from tests.utils import fixture
from renderers.karate import KarateRenderer
from parser import HttpRequest


class TestKarateRender(TestCase):

    def test_render(self):
        requests = HttpRequest.parse_file(fixture("file_one.http"))

        result = KarateRenderer.render(requests)

        print(result)

    def test_render_three(self):
        requests = HttpRequest.parse_file(fixture("file_three.http"))
        karate = KarateRenderer.render(requests)

        self.assertEqual("""Given url '/kittens'
    When method get
    Then status 200

""", karate)

    # def test_render_yaml(self):
    #     requests = HttpRequest.parse_file(fixture("file_one.http"))

    #     swagger = yaml.load(SwaggerYamlRenderer.render(requests))

    #     self.assertEqual(swagger['info']['title'], "Generated by Strut")
    #     self.assertEqual(len(swagger['paths']), 1)
